/// Pure-Dart model.  No Flutter dependency.
///
/// Holds the current board (with blanks) and the full solution
/// generated by [SudokuHomePage].
class SudokuPuzzle {
  final List<List<int>> board;
  final List<List<int>> solution;

  SudokuPuzzle(this.board, this.solution);
}
